name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Display version information
        run: rustup --version; cargo --version; rustc --version
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Build everything
        run: cargo build --all --all-targets
      - name: Run all unit tests
        run: cargo test --all
